cache:
  redis:
    addr: 127.0.0.1:6379
    db: 0
  type: redis
credentials:
  key: _
  secret: _
database:
  host: 127.0.0.1
  name: addrbookDB
  password: _
  port: 27017
  user: _
server:
  port: 8080
